title: BB Bushcraft
description: A collection of bushcraft methods, tipes and tricks!
theme: just-the-docs

url: https://braidwoodboy.github.io/bushcraft/
aux_links:
  "Disclaimer":
    - "https://braidwoodboy.github.io/bushcraft/dev/disclaimer.html"

callouts:
  warning:
      title: Warning
      color: red
  note:
      title: Note
      color: blue
  tip:
      title: Tip
      color: green
