title: BB Bushcraft
description: A collection of bushcraft methods, tipes and tricks!
theme: just-the-docs

url: https://braidwoodboy.github.io/testing

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

callouts:
  warning:
      title: Warning
      color: red
  note:
      title: Note
      color: blue
  tip:
      title: Tip
      color: green
